import { Injectable } from '@angular/core';

@Injectable()
export class EmployeeService {
  constructor() {}
  getdata() {
    return;
    [
      {
        _id: '63d0d7b3f4dc08db67d511d1',
        index: 0,
        guid: '09393917-fef3-4b87-9bb6-806bc507a8ed',
        isActive: false,
        balance: '$1,680.32',
        picture: 'http://placehold.it/32x32',
        age: 36,
        eyeColor: 'blue',
        name: 'Conway Schwartz',
        gender: 'male',
        company: 'BRAINCLIP',
        email: 'conwayschwartz@brainclip.com',
        phone: '+1 (811) 500-3007',
        address: '672 Knapp Street, Hartsville/Hartley, Hawaii, 2591',
        about:
          'Voluptate occaecat ullamco adipisicing tempor excepteur elit veniam tempor labore ea nulla. Officia do nisi est duis eu nisi reprehenderit. Officia pariatur labore labore officia commodo exercitation est anim sint. Reprehenderit incididunt aliquip duis minim. Lorem minim aliquip pariatur in do anim incididunt nulla amet eiusmod deserunt officia est cupidatat. Adipisicing eu proident eu nostrud velit amet.\r\n',
        registered: '2019-03-07T09:11:22 -06:-30',
        latitude: 45.429674,
        longitude: 102.508089,
        tags: ['minim', 'amet', 'do', 'mollit', 'laboris', 'duis', 'minim'],
        friends: [
          {
            id: 0,
            name: 'York Camacho',
          },
          {
            id: 1,
            name: 'Benton Kerr',
          },
          {
            id: 2,
            name: 'Ilene Pearson',
          },
        ],
        greeting: 'Hello, Conway Schwartz! You have 6 unread messages.',
        favoriteFruit: 'strawberry',
      },
      {
        _id: '63d0d7b3617b0455bc8a79a7',
        index: 1,
        guid: '3aedf9a1-43cc-43e6-ae42-6e3dc8790856',
        isActive: false,
        balance: '$3,931.70',
        picture: 'http://placehold.it/32x32',
        age: 26,
        eyeColor: 'blue',
        name: 'June Norton',
        gender: 'female',
        company: 'PROFLEX',
        email: 'junenorton@proflex.com',
        phone: '+1 (813) 404-3690',
        address: '181 Woodrow Court, Leming, Connecticut, 9411',
        about:
          'Cillum dolore excepteur incididunt labore aliqua sint qui ullamco laborum. Sit proident voluptate non ipsum magna aliquip in ex aute reprehenderit in Lorem commodo. Qui aliquip dolor qui aliquip excepteur quis.\r\n',
        registered: '2018-05-06T04:37:18 -06:-30',
        latitude: 10.266791,
        longitude: 47.654071,
        tags: [
          'nostrud',
          'ullamco',
          'ipsum',
          'dolor',
          'magna',
          'do',
          'officia',
        ],
        friends: [
          {
            id: 0,
            name: 'Mcmillan Mccarty',
          },
          {
            id: 1,
            name: 'Tiffany Weiss',
          },
          {
            id: 2,
            name: 'Sears Lewis',
          },
        ],
        greeting: 'Hello, June Norton! You have 9 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '63d0d7b3ea0997f87fb06d4a',
        index: 2,
        guid: 'bb4ba785-5f18-49fd-8ee6-ce487536c944',
        isActive: false,
        balance: '$1,909.50',
        picture: 'http://placehold.it/32x32',
        age: 33,
        eyeColor: 'blue',
        name: 'Mason Marks',
        gender: 'male',
        company: 'NAMEBOX',
        email: 'masonmarks@namebox.com',
        phone: '+1 (897) 588-3185',
        address: '947 Erasmus Street, Hillsboro, Kansas, 1980',
        about:
          'Sunt mollit amet ullamco non exercitation elit ea magna nisi. Sint esse voluptate aliquip mollit fugiat. Et ipsum nostrud cupidatat excepteur adipisicing. Consequat qui esse sit commodo occaecat. Qui sint elit cillum exercitation in ullamco sint nisi. Labore adipisicing culpa qui in aliqua. Anim qui dolor nostrud cillum aute aliquip reprehenderit in in ex in labore.\r\n',
        registered: '2021-09-03T02:04:11 -06:-30',
        latitude: 32.490068,
        longitude: 106.31533,
        tags: [
          'laboris',
          'nulla',
          'consectetur',
          'Lorem',
          'ut',
          'tempor',
          'aliquip',
        ],
        friends: [
          {
            id: 0,
            name: 'Jarvis Short',
          },
          {
            id: 1,
            name: 'Willa Lopez',
          },
          {
            id: 2,
            name: 'Lora Pitts',
          },
        ],
        greeting: 'Hello, Mason Marks! You have 4 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '63d0d7b3f97e02126d85623d',
        index: 3,
        guid: 'ef1ce857-3491-4479-b91c-166c7a8dda29',
        isActive: false,
        balance: '$2,559.94',
        picture: 'http://placehold.it/32x32',
        age: 30,
        eyeColor: 'brown',
        name: 'Williamson Graves',
        gender: 'male',
        company: 'UNI',
        email: 'williamsongraves@uni.com',
        phone: '+1 (869) 562-3775',
        address: '138 Loring Avenue, Zortman, Michigan, 8204',
        about:
          'Ullamco ad officia ut aliquip culpa deserunt commodo anim culpa. Nisi ad quis adipisicing ipsum enim id nulla est. Ut Lorem duis dolore sunt deserunt cillum irure veniam minim cupidatat veniam id. Eiusmod ipsum in magna ex sit aliquip labore.\r\n',
        registered: '2023-01-25T03:46:06 -06:-30',
        latitude: 71.876798,
        longitude: -3.85773,
        tags: ['in', 'consequat', 'velit', 'sint', 'duis', 'mollit', 'et'],
        friends: [
          {
            id: 0,
            name: 'Kelsey Dejesus',
          },
          {
            id: 1,
            name: 'Helene Walton',
          },
          {
            id: 2,
            name: 'Bowen Simmons',
          },
        ],
        greeting: 'Hello, Williamson Graves! You have 1 unread messages.',
        favoriteFruit: 'apple',
      },
      {
        _id: '63d0d7b379eeb5c4fd4bf10e',
        index: 4,
        guid: 'c6a721df-a2e4-41e3-920b-012db9e3995f',
        isActive: true,
        balance: '$3,940.22',
        picture: 'http://placehold.it/32x32',
        age: 37,
        eyeColor: 'brown',
        name: 'Mayra Ortiz',
        gender: 'female',
        company: 'TERRAGEN',
        email: 'mayraortiz@terragen.com',
        phone: '+1 (812) 496-3379',
        address: '377 Story Court, Washington, South Dakota, 6974',
        about:
          'Minim eiusmod in pariatur dolore reprehenderit mollit aliqua aute occaecat nisi consequat aliqua. Tempor occaecat laboris anim pariatur ex dolor fugiat exercitation in exercitation exercitation. Non culpa laborum eu excepteur enim aliquip consectetur elit enim anim voluptate officia. Sunt pariatur cupidatat sunt non laborum tempor irure consequat est velit et ullamco sunt. Pariatur esse ut dolore fugiat non fugiat laboris id aliqua minim sint sit excepteur. Enim magna elit ad dolore veniam nostrud culpa laborum quis officia sunt culpa. Qui sit id labore consectetur.\r\n',
        registered: '2019-04-22T12:28:19 -06:-30',
        latitude: 80.184903,
        longitude: 157.365012,
        tags: [
          'veniam',
          'laborum',
          'consequat',
          'consectetur',
          'adipisicing',
          'exercitation',
          'incididunt',
        ],
        friends: [
          {
            id: 0,
            name: 'Reese Howe',
          },
          {
            id: 1,
            name: 'Tanner Maddox',
          },
          {
            id: 2,
            name: 'Lela Dennis',
          },
        ],
        greeting: 'Hello, Mayra Ortiz! You have 6 unread messages.',
        favoriteFruit: 'strawberry',
      },
    ];
  }
}
